---
apiVersion: v1
kind: Namespace
metadata:
  name: django-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-appdeployment
  labels:
    app: django-app
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: yashwanthkotha/django-app:v1
        volumeMounts:
        - name: db-connection
          mountPath: /opt
      volumes:
      - name: db-connection
        configMap:
          name: django-cm
---
apiVersion: v1
kind: Service
metadata:
  name: django-appservice
  namespace: django-app
spec:
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort


          #env: 
          #- name: DB-PORT
          #valueFrom:
          # configMapKeyRef:
          #   name: django-cm
          #   key: db-port
