---
apiVersion: v1
kind: Namespace
metadata:
  name: django-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-appdeployment
  labels:
    app: django-app
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: yashwanthkotha/django-app:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-appservice
  namespace: django-app
spec:
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
